version: '3'
services:
  app:
    image: shahidnazirmhd/personal-service:1.0.0
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "8089:8088"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
